### ISSUE TITLE
(Browser)kotor 2 Saves don't register on browsers. 

### ISSUE THREAD

**Issue by Alpha-Wolf9933** [StarfishXeno/sotor#2]
I used to get Kotor 1 android saves modified on browsers (chromium, Firefox), but now it doesn't recognize the Kotor 2 saves or something. it's only with kotor 2, not the first one.

**Comment by StarfishXeno** [comment]
Could you upload a copy of a save with the issue?

**Comment by Alpha-Wolf9933** [comment]
![000005 - game4.zip](https://github.com/user-attachments/files/17089072/000005.-.game4.zip)

Here you go. When I choose all the files it doesn't do anything. but I can still modify Kotor 1 android saves.

**Comment by StarfishXeno** [comment]
I'm seeing what I can only assume is corruption of a bunch of values of a specific type. 
I can see this save has been edited before, or at least some form of cheats was used. 
Also, with my version of the game, loading the save and saving again removes most of the corrupted values, though not all, so the editor still complains.

Here are a bunch of questions to try and narrow it down:
1. This is from the android version of the game, correct?
2. Since the corruption is only with string values, was this save ever used with a non-English version of the game?
3. Are you using any mods? 
4. Did you use the browser version of SotOR to add all those items, or something else?
5. Did you do anything else out of ordinary with the save? 
6. What were the steps to this issue happening? Did you edit it and then the edited version immediately stopped loading? Or play for a while and they try to edit it again?

Also I just noticed that the web version doesn't show errors, but that's an easy fix.

**Comment by Alpha-Wolf9933** [comment]
1. Yes, It was from the android version 
 (I know you never said Sotor supported the android saves, but KOTOR 1 saves did work and Android save and PC saves are the same. I could run my PC saves on the android version)

2. The save was made in the English version of the game. 

3. Yes. TSLRCM and others like PartySwap, Extended Enclave and other minor mods. (though apparently mods don't do corruptible anything to the save, at least to my knowledge, I'll get to it)

4. If I could use the SoTOR to add items or modify any attributes I wouldn't bother you here, Items were earned in-game. Attributes on the other hand were added by a program called Game guardian(It's like cheat engine, just for Android)

5. Apart from the Attribute cheat mentioned earlier and Mods, nothing else. 

6. This issue was from the beginning. Saves do not show up at all. The screen stays at the "Please select a Save" even after selecting all the save files. 


Like I mentioned in point 3 and 4, Mods and Attribute cheat was used so I tried a clean run without Mods and Cheat engine hack.
The results were the same as I mentioned in point 6. I'm linking the clean save so you can see corruption if present. 

![000006 - game5.zip](https://github.com/user-attachments/files/17089868/000006.-.game5.zip)

**Comment by StarfishXeno** [comment]
Thanks. 
The clean save has the same issue and so far I don't see a pattern other than a bunch of fields containing garbage values. A lot of these aren't even used by the game, just holdovers from engine's NWN days, others just aren't important.
If it's some kind of a bug in that game's version, I could just allow this kind of corruption to load and replace the values with empty ones, but It could also be some weird intended change.
I'll think some more and try to come up with a solution. I don't play the phone ports myself, but it's nice to support them.

**Comment by StarfishXeno** [comment]
I've confirmed that it's not just your saves, and not just my code, at least. 
Got an android save of my own with the same issue, and K-GFF crashes trying to open these.

**Comment by Alpha-Wolf9933** [comment]
It seems to also corrupt the PC saves. I downloaded a PC save and checked if SoTOR worked on it to make sure, and it was fine. I modified the Skills to 15 for all then moved it to my Kotor 2 android saves. When it loaded everything was fine and I overwrote the save with an in-game save. Then SoTOR didn't recognize the save once again.

**Comment by StarfishXeno** [comment]
I've made 2 identical saves on PC and android to compare. 
Out of 800 corrupted fields in the android save, every single one of them was empty in the PC version.
So I'm concluding that the android version has a bug that causes empty strings to be saved incorrectly, and it should be safe to default these values to such. 
There IS still an issue of invalid values having a chance to load successfully, so I can't completely guarantee that it won't cause issues, but as far as I can tell, the PC version does the very same thing when loading android saves.

I've uploaded a new release, so you can check it out.
